nelmio_api_doc:
    documentation:
        info:
            title: ScooterVolt Catalog
            description: Catalog microservice for the ScooterVolt platform
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(\.json)?$).* 
