name: Test

on:
  push:
    branches: ["main", "*"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
      - name: Set up MongoDB
        run: |
          COUNTER=0
          while [[ $COUNTER -lt 60 ]] ; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:27017/ScooterVolt-Catalog)
              if [ "$STATUS" -eq 200 ]; then
                  echo "MongoDB is ready."
                  break
              fi
              sleep 2
              let COUNTER+=2
              echo "Waiting for MongoDB to initialize... ($COUNTER seconds so far)"
          done
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: composer test
